import "./globals.css";

// import cursor context provider
import CursorProvider from "@/components/CursorContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <CursorProvider>
          {children}
        </CursorProvider>
      </body>
    </html>
  );
}
